### ISSUE TITLE
Reports for experts/stakeholders

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/design#28] opened 2021-12-17 22:05 UTC
- how many visitors last week
- how many videos were watched
- which videos 
- how much traffic did we drive elsewhere?
- top searches
- number of ask the expert questions we received

QUARTERLY

**Comment by joenicolette** [comment] 2021-12-19 17:23
Note that this is ~a dupe of #15

**Closed** 2022-01-04 16:55 UTC
Labels: enhancement, High Priority
